name: util
description: util用 Dart パッケージ
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  logging: ^1.3.0

dev_dependencies:
  altive_lints: ^1.22.0
  custom_lint: ^0.7.6
  test:


