// Mocks generated by Mockito 5.4.6 from annotations
// in domain/test/src/tournament/tournament_create_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTournament_0 extends _i1.SmartFake implements _i2.Tournament {
  _FakeTournament_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CreateTournamentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTournamentUseCase extends _i1.Mock
    implements _i2.CreateTournamentUseCase {
  @override
  _i3.Future<_i2.Tournament> invoke({
    required String? title,
    required String? description,
    required String? startDate,
    required String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [], {
              #title: title,
              #description: description,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<_i2.Tournament>.value(
              _FakeTournament_0(
                this,
                Invocation.method(#invoke, [], {
                  #title: title,
                  #description: description,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i2.Tournament>.value(
              _FakeTournament_0(
                this,
                Invocation.method(#invoke, [], {
                  #title: title,
                  #description: description,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.Tournament>);
}
