name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  animated_reorderable_list: ^1.2.0
  base_ui:
    path: ../base_ui
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_animated_grid: ^1.0.0
  flutter_hooks: ^0.21.2
  flutter_reorderable_grid_view: ^5.5.0
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  injection:
    path: ../injection
  util:
    path: ../util

dev_dependencies:
  altive_lints: ^1.22.0
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true