
targets:
  $default:
    builders:
      # https://pub.dev/packages/flutter_gen_runner#configuration-file
      flutter_gen_runner:
        options: 
          output: lib/src/
          assets:
            outputs:
              package_parameter_enabled: true
