# 生成ファイルの出力先として git 管理されない `.dart_tool/flutter_gen` を指定するかどうか。
#
# Pub Workspace 利用だと利用不可 & 今後廃止される予定のため、false に設定する。
# 参考: https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
synthetic-package: false

# 翻訳のリソースが格納されているディレクトリ。
arb-dir: lib/src/l10n

# ファイル生成の際に基準となる翻訳ファイル。
#
# 日本語文言をベースに `arb_translate` パッケージで自動翻訳するために日本語に指定している。
# 文言が arb ファイルにて未翻訳の場合、自動生成ファイル上ではこの arb ファイルのものにフォールバックする。
template-arb-file: app_ja.arb

# 翻訳用に自動生成されるクラス名。
#
# 利用時の扱いやすさを考慮して、慣習的に短縮した命名にする。
output-class: L10n

# 自動生成されるファイル名。
output-localization-file: l10n.dart

# 生成されるクラスの getter を null 許容するかどうか。
#
# 呼び出し時の null チェックを簡略化するために false に設定する。
nullable-getter: false

# ファイル生成後に `dart format .` コマンドを実行するかどうか。
#
# `l10n.dart` の生成結果にフォーマットをかける必要があるため true にしておく。
format: true

# ロケールの優先順。
#
# 生成ファイルの `supportedLocales` へ追加されるロケールの順序（指定が無い場合はアルファベット順）に影響する。
# デバイスの設定言語に対応するものが存在しない場合のフォールバック先を英語にするために、英語を先頭に配置しておく。
preferred-supported-locales:
  - en
  - ja