name: injection
description: injection用 Dart パッケージ
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  cloud_firestore: ^5.0.0
  domain:
    path: ../domain
  firebase_auth: ^5.7.0
  http: ^1.4.0
  meta: ^1.16.0
  repository:
    path: ../repository
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  system:
    path: ../system
  util:
    path: ../util

dev_dependencies:
  altive_lints: ^1.22.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.6
  # system の Flutter SDK 依存パッケージを利用するために test ではなく flutter_test を利用する。
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

# flutter_test 実行時、他パッケージとの設定を合わせる必要があるために明記しておく。
flutter:
  uses-material-design: true

